name: Sync with Upstream
permissions:
  contents: write
on:
  schedule:
    - cron: "0 8 * * *"  # 每天北京时间16点执行（UTC+8）
  workflow_dispatch:     # 支持手动触发
jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Sync with alantang1977/X
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: alantang1977/X
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
